services:
  - type: web
    name: multi-modal-age-gender-classification
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port $PORT